services:
  postgres:
    image: postgres:latest
    container_name: newlester_docker
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: verysecret
      POSTGRES_DB: newsletterdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: